steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/jaspajjr/google-cloud-functions-http']

  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: [ 'build',
            '-t',
            'gcr.io/$PROJECT_ID/http-functions:$SHORT_SHA',
            '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Test
    args: [ 'run',
            '-it',
            'gcr.io/$PROJECT_ID/http-functions:$SHORT_SHA',
            '-t']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions',
      'deploy',
      'yo-son',
      '--trigger-http',
      '--runtime=python37'
    ]